config/routes.rb
Rails.application.routes.draw do
  resources :specialties, only: :none do
    get :autocomplete, on: :collection
  end

  resources :professionals, only: [:index, :show]

  get "loading" => "static#loading"
  root to: 'static#landing'
end

app/models/client.rb
class Client < ActiveRecord::Base
  include Nameable

  has_many :impressions
end

app/models/concerns/nameable.rb
module Nameable
  extend ActiveSupport::Concern

  included do
    validates_presence_of :name, :surnames
  end

  def complete_name
    [name, surnames].join(' ')
  end
end

app/models/impression.rb
class Impression < ActiveRecord::Base
  belongs_to :professional
  belongs_to :client

  validates_presence_of :professional, :client, :rating, :comment
  validates_inclusion_of :rating, in: 1..5

  after_save :update_professional_rating!

  private

  def update_professional_rating!
    professional.update_rating!
  end
end

app/models/professional.rb
class Professional < ActiveRecord::Base
  include Nameable

  has_and_belongs_to_many :specialties
  has_many :impressions

  scope :sort_by_rating, -> { order(arel_table[:rating].desc) }
  scope :sort_by_distance, -> { order(arel_table[:distance].asc) }
  scope :sort_by_best_price, -> { order(arel_table[:hourly_price].asc) }
  scope :sort_by_response_time, -> { order(arel_table[:average_response_time].asc) }

  def update_rating!
    self.rating = if impressions.any?
                    impressions.sum(:rating) / impressions.count.to_f
                  else
                    0
                  end
    save!
  end
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
  has_and_belongs_to_many :professionals

  scope :beginning_with, ->(term) { where(arel_table[:name].matches("#{term}%")) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  def index
    @professionals = if @specialty = Specialty.find_by_id(params[:specialty_id])
                       @term = @specialty.name
                       @specialty.professionals
                     else
                       Professional.all
                     end

    @sort_types = %w{ rating response_time distance best_price }

    @sort_type = params[:sort_type]
    unless @sort_types.include?(@sort_type)
      @sort_type = 'rating'
    end

    @professionals = @professionals.sort_by_rating if @sort_type == 'rating'
    @professionals = @professionals.sort_by_distance if @sort_type == 'distance'
    @professionals = @professionals.sort_by_best_price if @sort_type == 'best_price'
    @professionals = @professionals.sort_by_response_time if @sort_type == 'response_time'
  end

  def show
    @professional = Professional.find(params[:id])
  end
end

app/controllers/specialties_controller.rb
class SpecialtiesController < ApplicationController
  def autocomplete
    specialties = Specialty.beginning_with(params[:term])
    specialties_information = specialties.map do |specialty|
      { label: specialty.name, value: professionals_path(specialty_id: specialty.id) }
    end
    render json: specialties_information
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    [controller_name, action_name].join '-'
  end
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
  def short_distance_for(seconds)
    distance_of_time_in_words(seconds).
      gsub(/about/, '').
      gsub(/hours?/, 'h').
      gsub(/minutes?/, 'm')
  end
end

app/views/layouts/_conversation.html.slim
.chat-list-item
  .photo
    = image_tag "professionals/#{image}.png"
  .text
    .name
      span.name-text= name
      span.title= title
    .message
      span= message

app/views/layouts/_conversations.html.slim
.talk-sidebar
  .chat-list
    .chat-list-title
      .title
        span Conversations
        span.close style="cursor: pointer" = image_tag "close.png"

    = render 'layouts/conversation', name: 'John McNulty', title: 'Providers', image: 'roger',
      message: 'Hello! I just discovered you could reduce 40% your Internet expenses. Would you be interested?'
    = render 'layouts/conversation', name: 'Anna Cuesta', title: 'Bookkeeper', image: 'cristina',
      message: 'We have an interesting tool for freelancers that could trim down your taxes. How does it sound?'
    = render 'layouts/conversation', name: 'Peter Hans', title: 'Electronics', image: 'jan',
      message: 'Quick reminder: your new security alarm is on the way. You should receive it by tomorrow!'
    = render 'layouts/conversation', name: 'Clara Pérez', title: 'Customer support', image: 'iris',
      message: 'Done! I just enabled the option we talked about. You will receive your invoices on your house community expenses direct to your mail from now on.'

- content_for :custom_js do
  javascript:
    $('span.close').click(function(){
      $('.talk-sidebar').removeClass('shown', 1000);
    });

app/views/layouts/application.html.slim
doctype html
html
  head
    title Solvia Home
    link href=asset_path('favicon.png') rel="shortcut icon"
    = stylesheet_link_tag :application
    = csrf_meta_tags

  body class=body_class
    = yield
    = render 'layouts/conversations'
    = javascript_include_tag :application
    = yield :custom_js

app/views/professionals/index.html.slim
= render 'professionals/index/search'
= render 'professionals/index/results'

app/views/professionals/index/_filter.html.slim
.filters-section
  - @sort_types.each do |sort_type|
    - sort_name = sort_type.to_s.gsub(/_/, ' ')
    - clazz = (sort_type == @sort_type) ? 'active' : ''
    - url_params = { sort_type: sort_type }
    - url_params.merge!(specialty_id: @specialty.id) if @specialty.present?
    .filter-item class=clazz = link_to "Sort by #{sort_name}", url_params

app/views/professionals/index/_result.html.slim
.freelancers-list-item
  .intro-info
    .photo
      = image_tag "professionals/#{professional.name.downcase}.png"
    .name
      span= professional.complete_name
      span.titles= professional.specialties.pluck(:name).to_sentence.capitalize
    .rating
      .stars
        - professional.rating.round.times do
          = image_tag "star.svg"
    .response
      span
        = short_distance_for(professional.average_response_time * 60)
    .distance
      = image_tag "loc.svg"
      span
        = number_to_human(professional.distance, units: :distance)
    .price
      span
        = number_to_currency(professional.hourly_price)
        | /h
    .bg-helper

  .more-info
    .action-section.clearfix
      .medium-12.columns
        span.actions-wrapper
          a.button.rating Rate
          a.button.talk Talk
          a.button.hire Hire
    .reviews-section.row
      - professional.impressions.each do |impression|
        .medium-3.columns= impression.client.complete_name
        .medium-9.columns.comment-box
          - impression.rating.round.times do
            = image_tag "star.svg"
          p.comment= impression.comment

app/views/professionals/index/_results.html.slim
.freelancers-list-section
  .row.row-full
    .medium-12.columns
      = render 'professionals/index/filter'
      .freelancers-list
        - @professionals.each do |professional|
          = render 'professionals/index/result', professional: professional

- content_for :custom_js do
  javascript:
    $('.freelancers-list-item').click(function(){
      var isNotMe = !$(this).hasClass('expanded');
      $('.expanded').removeClass('expanded');
      if(isNotMe) $(this).addClass('expanded');
    });

app/views/professionals/index/_search.html.slim
.header-section
  .row.row-full
    .medium-3.columns
      .logo
        = image_tag "logo.svg"
    .medium-6.columns
      .search-box
        .type-dropdown
          .options
            .option
              span Professionals
            .option
              span Advisors
        = text_field_tag :name, @term, id: 'autocomplete', placeholder: 'What are you looking for?'
    .medium-3.columns
      .head-user.talker style="cursor: pointer"
        = image_tag "head-user.png"

- content_for :custom_js do
  javascript:
    $(document).ready(function(){
      var autocompleteInput = $('input#autocomplete');
      autocompleteInput.autocomplete({
        source: "#{ escape_javascript autocomplete_specialties_path }.json",
        select: function(event, ui){
          window.location.href = ui.item.value;
          $('input#autocomplete').remove();
        }
      });
      autocompleteInput.focus();
    });

    $('.talker').click(function(){
      $('.talk-sidebar').addClass('shown', 1000);
    });

app/views/professionals/show.html.slim
h1= @professional.complete_name

app/views/specialties/index.html.slim
h1 Specialties
= text_field_tag :name, '', id: 'autocomplete', placeholder: 'Type the name here...'

- content_for :custom_js do
  javascript:
    $(document).ready(function(){
      var autocompleteInput = $('input#autocomplete');
      autocompleteInput.autocomplete({
        source: "#{ escape_javascript autocomplete_specialties_path }.json",
        select: function(event, ui){
          window.location.href = ui.item.value;
          $('input#autocomplete').remove();
        }
      });
      autocompleteInput.focus();
    });